name: Simulación CI - Contador Interactivo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Verificar archivos importantes
      run: |
        test -f index.html && echo "✔ index.html encontrado"
        test -f style.css && echo "✔ style.css encontrado"
        test -f script.js && echo "✔ script.js encontrado"

    - name: Verificación completada
      run: echo "✅ Todo está en orden. Proyecto listo para previsualizarse."
