name: Entrega Continua - Preproducción

on:
  push:
    branches:
      - main  # Se ejecutará cuando subas cambios a la rama main
  pull_request:
    branches:
      - main

jobs:
  deploy-preprod:
    runs-on: ubuntu-latest  # Usa el sistema Ubuntu en el servidor de GitHub

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar entorno de preproducción
      run: |
        echo "Configurando entorno de preproducción..."
        # Aquí podrías ejecutar comandos para simular el despliegue sin hacerlo realmente

    - name: Simular despliegue a preproducción
      run: |
        echo "Simulando despliegue a preproducción..."
        echo "Proyecto listo para previsualización, pero aún no en producción."

    - name: Verificación completada
      run: echo "✅ Entorno de preproducción configurado correctamente"
