name: Entrega Continua - Preproducción

on:
  push:
    branches:
      - main

jobs:
  deploy-to-preproduction:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v2

    - name: Crear entorno de preproducción
      run: |
        mkdir -p preproduction
        cp -r * preproduction/
        
    - name: Subir artefacto (versión construida)
      uses: actions/upload-artifact@v2
      with:
        name: preproduction-version
        path: preproduction/
