name: Entrega Continua - Preproducción

on:
  push:
    branches:
      - main  # Se activa cuando subes algo a la rama principal
  pull_request:
    branches:
      - main

jobs:
  deploy-preprod:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Netlify CLI
        run: npm install -g netlify-cli

      - name: Desplegar a preproducción en Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify deploy --dir=./ --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN --message="Deploy de preproducción" --json
