name: Entrega Continua - Preproducción

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-to-preproduction:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Crear entorno de preproducción
      run: |
        echo "Simulando preproducción... Se crea la versión para revisión"
        mkdir -p preproduction
        cp -r * preproduction/
        echo "✅ Preproducción lista para revisión."

    - name: Verificación completada
      run: echo "✅ El entorno de preproducción está listo. No se ha desplegado a producción."
