name: Deploy Preproducción

on:
  push:
    branches:
      - main  # o la rama que estés usando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Netlify CLI
        run: npm install -g netlify-cli

      - name: Desplegar a Netlify (preproducción)
        env:
          NETLIFY_SITE_ID: tu-id-de-sitio-netlify
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: netlify deploy --dir=./ --site=$NETLIFY_SITE_ID --auth=$DEPLOY_TOKEN --message="Deploy de preproducción" --json
