name: Deploy Preproducción

on:
  push:
    branches:
      - main  # Se ejecuta cuando se suben cambios a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Netlify CLI
        run: npm install -g netlify-cli

      - name: Desplegar a Netlify (preproducción)
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: netlify deploy --dir=./ --site=$NETLIFY_SITE_ID --auth=$DEPLOY_TOKEN --message="Deploy de preproducción"
